all:
	cd DCIHM && make && cd ..
	cd DCOM && make && cd ..
	cd DDF && make && cd ..
	cd DEC && make && cd ..
	cd DEF && make && cd ..
	cd DesFen && make && cd ..
	cd DICIHM && make && cd ..
	cd DLxIHM && make && cd ..
	cd DPOU && make && cd ..
	cd DPU && make && cd ..
	cd DSIHM && make && cd ..
	cd DSyIHM && make && cd ..
	cd DTA && make && cd ..
	cd DTU && make && cd ..
	cd FDFen && make && cd ..
	cd Glossaire && make && cd ..
	cd GPU && make && cd ..
	cd GuideDeStyle && make && cd ..
	cd LxqOG && make && cd ..
	cd LxqVT && make && cd ..
	cd Makefile && make && cd ..
	cd Maquettes && make && cd ..
	cd MSIHM && make && cd ..
	cd MU && make && cd ..
	cd PHTU && make && cd ..
	cd SPU && make && cd ..
	cd TCUM && make && cd ..
	cd TC-U_TU-C && make && cd ..
	cd TICAR && make && cd ..
	cd TMesU && make && cd ..
	cd TTU-DF && make && cd ..
